FROM testcontainers/sshd
RUN apk add --no-cache python3 python3-pip nmap
COPY requirements.txt /
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
CMD ["/usr/sbin/sshd", "-D"]
