version: '3'
# 网络分配原则： 172.30.网络.节点  n1为起始点,ip定位254(和.1网关避开)
networks:
   netrork_1:
      ipam:
         config:
         - subnet: 172.30.1.0/24
   netrork_2:
      ipam:
         config:
         - subnet: 172.30.2.0/24
   netrork_3:
      ipam:
         config:
         - subnet: 172.30.3.0/24
   netrork_4:
      ipam:
         config:
         - subnet: 172.30.4.0/24
   netrork_5:
      ipam:
         config:
         - subnet: 172.30.5.0/24
   netrork_6:
      ipam:
         config:
         - subnet: 172.30.6.0/24

services:
  n1:
    build: target_node
    container_name: n1
    restart: always
    command: ['bash','-c','while :; do sleep 1; done']
    volumes:
      - './docker_root_shared/:/root/'
      - './ssh_find_script/:/ssh_find_script/'
      - './n1_tmp/:/tmp/'
    networks:
      netrork_1:
        ipv4_address: 172.30.1.254
  n2:
    build: target_node
    container_name: n2
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_1:
        ipv4_address: 172.30.1.2
      netrork_2:
        ipv4_address: 172.30.2.2
  n3:
    build: target_node
    container_name: n3
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_1:
        ipv4_address: 172.30.1.3
      netrork_3:
        ipv4_address: 172.30.3.3
  n4:
    build: target_node
    container_name: n4
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_1:
        ipv4_address: 172.30.1.4
      netrork_4:
        ipv4_address: 172.30.4.4
  n5:
    build: target_node
    container_name: n5
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_1:
        ipv4_address: 172.30.1.5
      netrork_5:
        ipv4_address: 172.30.5.5
  n6:
    build: target_node
    container_name: n6
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_2:
        ipv4_address: 172.30.2.6
  n7:
    build: target_node
    container_name: n7
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_2:
        ipv4_address: 172.30.2.7
  n8:
    build: target_node
    container_name: n8
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_3:
        ipv4_address: 172.30.3.8
      netrork_4:
        ipv4_address: 172.30.4.8
      netrork_6:
        ipv4_address: 172.30.6.8
  n9:
    build: target_node
    container_name: n9
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_5:
        ipv4_address: 172.30.5.9
  n10:
    build: target_node
    container_name: n10
    restart: always
    volumes:
      - ./docker_root_shared/:/root/
    networks:
      netrork_6:
        ipv4_address: 172.30.6.10
